### PR TITLE
docs: Update env file and project setup.

### PR DESCRIPTION
**Pull request by notheowner**
Uncomment Controller DB URL.
Update Scanner DB URL default to Golbat.
Add ReactMap and Golbat Project Setup for hot reloading of geofences.

### CODE REVIEW

**Comment by Fabio1988** [comment]
probably we should keep that file also in sync :) 

https://github.com/TurtIeSocks/Koji/blob/main/docker-compose.example.yml

**Comment by clburlison** [comment]
I think this _might_ be more confusing for legacy peeps.

The config options are:
RDM only
``` 
      # Your Golbat or RDM database
      SCANNER_DB_URL: 'mysql://rdm_user:rdm_password@host:3306/rdm_database'
```
RDM + Golbat (Hybrid)
```
      # Your Golbat or RDM database
      SCANNER_DB_URL: 'mysql://golbat_user:golbat_password@host:3306/golbat_database'
      # Your Dragonite (if using) or RDM database (if you're using a hybrid Golbat/RDM setup)
      CONTROLLER_DB_URL: 'mysql://rdm_user:rdm_password@host:3306/rdm_database'
```

Dragonite + Golbat
```
      # Your Golbat or RDM database
      SCANNER_DB_URL: 'mysql://golbat_user:golbat_password@host:3306/golbat_database'
      # Your Dragonite (if using) or RDM database (if you're using a hybrid Golbat/RDM setup)
      CONTROLLER_DB_URL: 'mysql://dragonite_user:dragonite_password@host:3306/dragonite_database'
```

I've turned off my RDM instances so I'm not sure how Koji works if someone sets SCANNER + CONTROLLER to an RDM instance.

Now's a great time to deprecate RDM support and remove all that code. _nudge Turtle_ 😉🙃

**Comment by notheowner** [comment]
> I think this _might_ be more confusing for legacy peeps.
> 
> The config options are: RDM only
> 
> ```
>       # Your Golbat or RDM database
>       SCANNER_DB_URL: 'mysql://rdm_user:rdm_password@host:3306/rdm_database'
> ```
> 
> RDM + Golbat (Hybrid)
> 
> ```
>       # Your Golbat or RDM database
>       SCANNER_DB_URL: 'mysql://golbat_user:golbat_password@host:3306/golbat_database'
>       # Your Dragonite (if using) or RDM database (if you're using a hybrid Golbat/RDM setup)
>       CONTROLLER_DB_URL: 'mysql://rdm_user:rdm_password@host:3306/rdm_database'
> ```
> 
> Dragonite + Golbat
> 
> ```
>       # Your Golbat or RDM database
>       SCANNER_DB_URL: 'mysql://golbat_user:golbat_password@host:3306/golbat_database'
>       # Your Dragonite (if using) or RDM database (if you're using a hybrid Golbat/RDM setup)
>       CONTROLLER_DB_URL: 'mysql://dragonite_user:dragonite_password@host:3306/dragonite_database'
> ```
> 
> I've turned off my RDM instances so I'm not sure how Koji works if someone sets SCANNER + CONTROLLER to an RDM instance.
> 
> Now's a great time to deprecate RDM support and remove all that code. _nudge Turtle_ 😉🙃

Yeah, I didn't touch much of the wording, because I don't know when Turtle wants to ditch RDM support.

**Review by TurtIeSocks — APPROVED** [review]
Apologies for the delay on this, looks great, thank you for the contribution!

**Pull request merged**
